// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufuy1NFLjKe65_J5VvaHS-gLism3Xaio',
    appId: '1:241463995180:web:3f99605d4d91bcb7c19a89',
    messagingSenderId: '241463995180',
    projectId: 'chat-app-3b4e5',
    authDomain: 'chat-app-3b4e5.firebaseapp.com',
    storageBucket: 'chat-app-3b4e5.appspot.com',
    measurementId: 'G-0FQ986RM9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPmU31VByEEDjaPJOkKZVqJt74fpVuKB0',
    appId: '1:241463995180:android:aab7254f8d8e9a87c19a89',
    messagingSenderId: '241463995180',
    projectId: 'chat-app-3b4e5',
    storageBucket: 'chat-app-3b4e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzK_eOvpIpu_8kHCpRmWBOJPS16jj7pw',
    appId: '1:241463995180:ios:910348b2476e8b49c19a89',
    messagingSenderId: '241463995180',
    projectId: 'chat-app-3b4e5',
    storageBucket: 'chat-app-3b4e5.appspot.com',
    iosClientId: '241463995180-p0kspj8grtiuohr72qpf6n2icn03c9ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
